### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by SatanuG** [shauryr/ACL-anthology-corpus#1]
Hi,
I was wondering if you might have the timeline through which (I think it is till 2022, but what would be the starting year) this data was collected.

Best,
Satanu.

**Comment by shauryr** [comment]
you mean the start year? when was the first paper in ACL published?

**Comment by SatanuG** [comment]
Yes. Do you mean that this is a collection from the inception of ACL till 2022?
I was wondering if it was possible to get the year of publication of the papers.

**Comment by shauryr** [comment]
yes. This collection has everything from ACL till Sept'22. We are working on getting the year of the papers soon! That information if already there in the bib files. But having it in the pandas dataframe would be more useful.

**Comment by shauryr** [comment]
https://github.com/shauryr/ACL-anthology-corpus#how-is-this-different-from-what-acl-anthology-provides-and-what-already-exists - collection has been updated with dates
