### ISSUE TITLE
host data on zenodo

### ISSUE THREAD

**Issue by mayq97** [shauryr/ACL-anthology-corpus#5]
great work!!!, could you please host this dataset on the zenodo?
google drive is unavailable to people in china.

**Comment by qolina** [comment]
Thanks for your suggestion. We will work on this soon, providing world-wide access to the corpus.

**Comment by shauryr** [comment]
hi! The data is available on [https://huggingface.co/datasets/ACL-OCL/acl-anthology-corpus](https://huggingface.co/datasets/ACL-OCL/acl-anthology-corpus )
We are working on Zenodo upload as well, once we have a final version which has all the data! Thank you for your patience

**Comment by mayq97** [comment]
Thank you very much
