### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Wang-Yufei** [shauryr/ACL-anthology-corpus#6]
Hi Shaurya！
I want  to ask about some details of this dataset, such as what year the data source is from and what conferences are included.
Besides,  are 3 and 4 in the picture below the same batch of papers?
I would appreciate it if you could answer me.
Thanks!
<img width="841" alt="image" src="https://user-images.githubusercontent.com/59252906/210049832-121678e3-1ced-4633-b839-eb5e4e6086f4.png">

**Comment by shauryr** [comment]
Hello!
Thank you for reaching out! sorry for the late response:

"what year the data source" - 1953 to September'2022
"and what conferences are included" - all conferences on ACL Anthology
"Besides, are 3 and 4 in the picture below the same batch of papers" - Mostly yes! if there is a missing paper it is most probably that the full-text extraction failed for it
